# Generated by Django 4.2.3 on 2023-07-18 09:44

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='msisdn',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31),
        ),
    ]
