# Generated by Django 4.2.3 on 2023-07-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_requests', '0002_alter_requests_msisdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
