# Generated by Django 4.2.3 on 2023-07-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_requests', '0003_requests_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='agreement',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
