# Generated by Django 4.2.3 on 2023-07-20 11:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('landing_requests', '0004_requests_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='msisdn',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
