# Generated by Django 4.2.3 on 2023-07-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_requests', '0005_alter_requests_msisdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
